In [14]:
import numpy as np
import pandas as pd

In [15]:
df = pd.read_csv("../dataset/spam.csv", encoding="latin-1")

In [16]:
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   str
 1   v2          5572 non-null   str
 2   Unnamed: 2  50 non-null     str
 3   Unnamed: 3  12 non-null     str
 4   Unnamed: 4  6 non-null      str
dtypes: str(5)
memory usage: 217.8 KB

In [18]:
df.shape

(5572, 5)

In [19]:
df.isna().sum()

v1               0
v2               0
Unnamed: 2    5522
Unnamed: 3    5560
Unnamed: 4    5566
dtype: int64

In [20]:
df.drop(["Unnamed: 2","Unnamed: 3", "Unnamed: 4"], axis=1, inplace=True)

In [27]:
df.columns = ["label", "message"]

df.head()

   label                                            message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [23]:
df.duplicated().sum()

np.int64(403)

In [24]:
df = df.drop_duplicates()

In [25]:
df["label"] = df["label"].map({
        "ham": 0,
        "spam": 1
    })