In [1]:
import numpy as np
import pandas as pd
import nltk

In [2]:
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Asus\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Asus\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Asus\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Asus\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\Asus\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [3]:
import sys
sys.path.append("../src")

from eda_preprocessing import load_clean_data
from nlp_preprocessing import preprocess_text

In [4]:
df = load_clean_data("../dataset/spam.csv")

df.head()

   label                                            message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [5]:
df.shape

(5169, 2)

In [6]:
df.info()

<class 'pandas.DataFrame'>
Index: 5169 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   label    5169 non-null   int64
 1   message  5169 non-null   str
dtypes: int64(1), str(1)
memory usage: 121.1 KB

In [7]:
df.sample(5)

      label                                            message
4164      1  Dear Voucher Holder, To claim this weeks offer...
1750      0                         Got it..mail panren paru..
2395      0             Babe, I'm back ... Come back to me ...
1549      0  Dude sux for snake. He got old and raiden got ...
3614      0  I enjoy watching and playing football and bask...

In [8]:
df["processed_message"] = df["message"].apply(preprocess_text)

In [9]:
df[["message", "processed_message"]].head()

,message,processed_message
0,"Go until jurong point, crazy.. Available only ...",go jurong point crazi avail bugi n great world...
1,Ok lar... Joking wif u oni...,ok lar joke wif u oni
2,Free entry in 2 a wkly comp to win FA Cup fina...,free entri wkli comp win fa cup final tkt st m...
3,U dun say so early hor... U c already then say...,u dun say earli hor u c alreadi say
4,"Nah I don't think he goes to usf, he lives aro...",nah dont think goe usf live around though

In [10]:
df.to_csv( "../dataset/spam_processed.csv", index=False )